properties([parameters([string(description: 'Provide name to create IAM user with default password welcome123', name: 'USER_NAME'), string(description: 'Provide policy ARN to give access to IAM user', name: 'ARN')])])

pipeline {
  agent {
    kubernetes {
      defaultContainer 'jenkins-slave-general'
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: jenkins-slave-general
            image: shakilife/awsagent:v1.1
            command:
            - cat
            tty: true
        '''
    }
  }
    environment {
    AWS_DEFAULT_REGION="us-east-1"
  }
  stages{
      stage('Git Clone') {
          steps {
              git branch: 'main', url: 'https://github.com/shakilife/DevOps'
          }
      }
      stage('Create IAM user') {
          steps {
             withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-auto-user', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
              sh 'pwd ; ls -ltr'
              sh 'cd /home/jenkins/agent/workspace/aws/iam_user_creation && bash iam_creation.sh $USER_NAME $ARN'
             }
          }
      }
  }
  }