properties([parameters([string(description: 'user name to create user on aws iam', name: 'USER_NAME')])])
properties([parameters([string(description: 'please put ARN of any policy which you want to give access to user', name: 'ARN')])])


pipeline {
  agent {
    kubernetes {
      defaultContainer 'jenkins-slave-general'
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: jenkins-slave-general
            image: shakilife/awsagent:v1.1
            command:
            - cat
            tty: true
        '''
    }
  }
    environment {
    AWS_DEFAULT_REGION="us-east-1"
  }
  stages {
    stage('Check version') {
      steps {
        withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-auto-user', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
             cd /home/jenkins/agent/workspace/aws/iam_creation && bash iam_creation.sh $USER_NAME $ARN
          '''

          }
      }
    }
  }
}
